# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexanderfb/Projects/isekai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexanderfb/Projects/isekai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexanderfb/Projects/isekai/CMakeFiles /home/alexanderfb/Projects/isekai/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexanderfb/Projects/isekai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named isekai

# Build rule for target.
isekai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isekai
.PHONY : isekai

# fast build rule for target.
isekai/fast:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/build
.PHONY : isekai/fast

#=============================================================================
# Target rules for targets named libvcol

# Build rule for target.
libvcol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libvcol
.PHONY : libvcol

# fast build rule for target.
libvcol/fast:
	$(MAKE) -f libs/libvcol/CMakeFiles/libvcol.dir/build.make libs/libvcol/CMakeFiles/libvcol.dir/build
.PHONY : libvcol/fast

#=============================================================================
# Target rules for targets named camgraph

# Build rule for target.
camgraph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camgraph
.PHONY : camgraph

# fast build rule for target.
camgraph/fast:
	$(MAKE) -f libs/camgraph/CMakeFiles/camgraph.dir/build.make libs/camgraph/CMakeFiles/camgraph.dir/build
.PHONY : camgraph/fast

#=============================================================================
# Target rules for targets named libtwin

# Build rule for target.
libtwin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libtwin
.PHONY : libtwin

# fast build rule for target.
libtwin/fast:
	$(MAKE) -f libs/libtwin/CMakeFiles/libtwin.dir/build.make libs/libtwin/CMakeFiles/libtwin.dir/build
.PHONY : libtwin/fast

#=============================================================================
# Target rules for targets named camin

# Build rule for target.
camin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camin
.PHONY : camin

# fast build rule for target.
camin/fast:
	$(MAKE) -f libs/camin/CMakeFiles/camin.dir/build.make libs/camin/CMakeFiles/camin.dir/build
.PHONY : camin/fast

#=============================================================================
# Target rules for targets named libgoki

# Build rule for target.
libgoki: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libgoki
.PHONY : libgoki

# fast build rule for target.
libgoki/fast:
	$(MAKE) -f libs/libgoki/CMakeFiles/libgoki.dir/build.make libs/libgoki/CMakeFiles/libgoki.dir/build
.PHONY : libgoki/fast

src/action.o: src/action.c.o

.PHONY : src/action.o

# target to build an object file
src/action.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/action.c.o
.PHONY : src/action.c.o

src/action.i: src/action.c.i

.PHONY : src/action.i

# target to preprocess a source file
src/action.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/action.c.i
.PHONY : src/action.c.i

src/action.s: src/action.c.s

.PHONY : src/action.s

# target to generate assembly for a file
src/action.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/action.c.s
.PHONY : src/action.c.s

src/animate.o: src/animate.c.o

.PHONY : src/animate.o

# target to build an object file
src/animate.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/animate.c.o
.PHONY : src/animate.c.o

src/animate.i: src/animate.c.i

.PHONY : src/animate.i

# target to preprocess a source file
src/animate.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/animate.c.i
.PHONY : src/animate.c.i

src/animate.s: src/animate.c.s

.PHONY : src/animate.s

# target to generate assembly for a file
src/animate.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/animate.c.s
.PHONY : src/animate.c.s

src/audition.o: src/audition.c.o

.PHONY : src/audition.o

# target to build an object file
src/audition.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/audition.c.o
.PHONY : src/audition.c.o

src/audition.i: src/audition.c.i

.PHONY : src/audition.i

# target to preprocess a source file
src/audition.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/audition.c.i
.PHONY : src/audition.c.i

src/audition.s: src/audition.c.s

.PHONY : src/audition.s

# target to generate assembly for a file
src/audition.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/audition.c.s
.PHONY : src/audition.c.s

src/b64.o: src/b64.c.o

.PHONY : src/b64.o

# target to build an object file
src/b64.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/b64.c.o
.PHONY : src/b64.c.o

src/b64.i: src/b64.c.i

.PHONY : src/b64.i

# target to preprocess a source file
src/b64.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/b64.c.i
.PHONY : src/b64.c.i

src/b64.s: src/b64.c.s

.PHONY : src/b64.s

# target to generate assembly for a file
src/b64.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/b64.c.s
.PHONY : src/b64.c.s

src/backlog.o: src/backlog.c.o

.PHONY : src/backlog.o

# target to build an object file
src/backlog.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/backlog.c.o
.PHONY : src/backlog.c.o

src/backlog.i: src/backlog.c.i

.PHONY : src/backlog.i

# target to preprocess a source file
src/backlog.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/backlog.c.i
.PHONY : src/backlog.c.i

src/backlog.s: src/backlog.c.s

.PHONY : src/backlog.s

# target to generate assembly for a file
src/backlog.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/backlog.c.s
.PHONY : src/backlog.c.s

src/callback.o: src/callback.c.o

.PHONY : src/callback.o

# target to build an object file
src/callback.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/callback.c.o
.PHONY : src/callback.c.o

src/callback.i: src/callback.c.i

.PHONY : src/callback.i

# target to preprocess a source file
src/callback.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/callback.c.i
.PHONY : src/callback.c.i

src/callback.s: src/callback.c.s

.PHONY : src/callback.s

# target to generate assembly for a file
src/callback.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/callback.c.s
.PHONY : src/callback.c.s

src/channel.o: src/channel.c.o

.PHONY : src/channel.o

# target to build an object file
src/channel.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/channel.c.o
.PHONY : src/channel.c.o

src/channel.i: src/channel.c.i

.PHONY : src/channel.i

# target to preprocess a source file
src/channel.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/channel.c.i
.PHONY : src/channel.c.i

src/channel.s: src/channel.c.s

.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/channel.c.s
.PHONY : src/channel.c.s

src/chunker.o: src/chunker.c.o

.PHONY : src/chunker.o

# target to build an object file
src/chunker.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/chunker.c.o
.PHONY : src/chunker.c.o

src/chunker.i: src/chunker.c.i

.PHONY : src/chunker.i

# target to preprocess a source file
src/chunker.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/chunker.c.i
.PHONY : src/chunker.c.i

src/chunker.s: src/chunker.c.s

.PHONY : src/chunker.s

# target to generate assembly for a file
src/chunker.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/chunker.c.s
.PHONY : src/chunker.c.s

src/client.o: src/client.c.o

.PHONY : src/client.o

# target to build an object file
src/client.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/client.c.o
.PHONY : src/client.c.o

src/client.i: src/client.c.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/client.c.i
.PHONY : src/client.c.i

src/client.s: src/client.c.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/client.c.s
.PHONY : src/client.c.s

src/datafile.o: src/datafile.c.o

.PHONY : src/datafile.o

# target to build an object file
src/datafile.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile.c.o
.PHONY : src/datafile.c.o

src/datafile.i: src/datafile.c.i

.PHONY : src/datafile.i

# target to preprocess a source file
src/datafile.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile.c.i
.PHONY : src/datafile.c.i

src/datafile.s: src/datafile.c.s

.PHONY : src/datafile.s

# target to generate assembly for a file
src/datafile.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile.c.s
.PHONY : src/datafile.c.s

src/datafile/xml.o: src/datafile/xml.c.o

.PHONY : src/datafile/xml.o

# target to build an object file
src/datafile/xml.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile/xml.c.o
.PHONY : src/datafile/xml.c.o

src/datafile/xml.i: src/datafile/xml.c.i

.PHONY : src/datafile/xml.i

# target to preprocess a source file
src/datafile/xml.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile/xml.c.i
.PHONY : src/datafile/xml.c.i

src/datafile/xml.s: src/datafile/xml.c.s

.PHONY : src/datafile/xml.s

# target to generate assembly for a file
src/datafile/xml.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/datafile/xml.c.s
.PHONY : src/datafile/xml.c.s

src/ezxml.o: src/ezxml.c.o

.PHONY : src/ezxml.o

# target to build an object file
src/ezxml.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ezxml.c.o
.PHONY : src/ezxml.c.o

src/ezxml.i: src/ezxml.c.i

.PHONY : src/ezxml.i

# target to preprocess a source file
src/ezxml.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ezxml.c.i
.PHONY : src/ezxml.c.i

src/ezxml.s: src/ezxml.c.s

.PHONY : src/ezxml.s

# target to generate assembly for a file
src/ezxml.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ezxml.c.s
.PHONY : src/ezxml.c.s

src/files.o: src/files.c.o

.PHONY : src/files.o

# target to build an object file
src/files.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/files.c.o
.PHONY : src/files.c.o

src/files.i: src/files.c.i

.PHONY : src/files.i

# target to preprocess a source file
src/files.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/files.c.i
.PHONY : src/files.c.i

src/files.s: src/files.c.s

.PHONY : src/files.s

# target to generate assembly for a file
src/files.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/files.c.s
.PHONY : src/files.c.s

src/hs/hsdecode.o: src/hs/hsdecode.c.o

.PHONY : src/hs/hsdecode.o

# target to build an object file
src/hs/hsdecode.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsdecode.c.o
.PHONY : src/hs/hsdecode.c.o

src/hs/hsdecode.i: src/hs/hsdecode.c.i

.PHONY : src/hs/hsdecode.i

# target to preprocess a source file
src/hs/hsdecode.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsdecode.c.i
.PHONY : src/hs/hsdecode.c.i

src/hs/hsdecode.s: src/hs/hsdecode.c.s

.PHONY : src/hs/hsdecode.s

# target to generate assembly for a file
src/hs/hsdecode.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsdecode.c.s
.PHONY : src/hs/hsdecode.c.s

src/hs/hsencode.o: src/hs/hsencode.c.o

.PHONY : src/hs/hsencode.o

# target to build an object file
src/hs/hsencode.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsencode.c.o
.PHONY : src/hs/hsencode.c.o

src/hs/hsencode.i: src/hs/hsencode.c.i

.PHONY : src/hs/hsencode.i

# target to preprocess a source file
src/hs/hsencode.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsencode.c.i
.PHONY : src/hs/hsencode.c.i

src/hs/hsencode.s: src/hs/hsencode.c.s

.PHONY : src/hs/hsencode.s

# target to generate assembly for a file
src/hs/hsencode.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/hs/hsencode.c.s
.PHONY : src/hs/hsencode.c.s

src/ipc/netipc.o: src/ipc/netipc.c.o

.PHONY : src/ipc/netipc.o

# target to build an object file
src/ipc/netipc.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ipc/netipc.c.o
.PHONY : src/ipc/netipc.c.o

src/ipc/netipc.i: src/ipc/netipc.c.i

.PHONY : src/ipc/netipc.i

# target to preprocess a source file
src/ipc/netipc.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ipc/netipc.c.i
.PHONY : src/ipc/netipc.c.i

src/ipc/netipc.s: src/ipc/netipc.c.s

.PHONY : src/ipc/netipc.s

# target to generate assembly for a file
src/ipc/netipc.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/ipc/netipc.c.s
.PHONY : src/ipc/netipc.c.s

src/item.o: src/item.c.o

.PHONY : src/item.o

# target to build an object file
src/item.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/item.c.o
.PHONY : src/item.c.o

src/item.i: src/item.c.i

.PHONY : src/item.i

# target to preprocess a source file
src/item.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/item.c.i
.PHONY : src/item.c.i

src/item.s: src/item.c.s

.PHONY : src/item.s

# target to generate assembly for a file
src/item.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/item.c.s
.PHONY : src/item.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/main.c.s
.PHONY : src/main.c.s

src/mobile.o: src/mobile.c.o

.PHONY : src/mobile.o

# target to build an object file
src/mobile.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/mobile.c.o
.PHONY : src/mobile.c.o

src/mobile.i: src/mobile.c.i

.PHONY : src/mobile.i

# target to preprocess a source file
src/mobile.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/mobile.c.i
.PHONY : src/mobile.c.i

src/mobile.s: src/mobile.c.s

.PHONY : src/mobile.s

# target to generate assembly for a file
src/mobile.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/mobile.c.s
.PHONY : src/mobile.c.s

src/plugin.o: src/plugin.c.o

.PHONY : src/plugin.o

# target to build an object file
src/plugin.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugin.c.o
.PHONY : src/plugin.c.o

src/plugin.i: src/plugin.c.i

.PHONY : src/plugin.i

# target to preprocess a source file
src/plugin.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugin.c.i
.PHONY : src/plugin.c.i

src/plugin.s: src/plugin.c.s

.PHONY : src/plugin.s

# target to generate assembly for a file
src/plugin.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugin.c.s
.PHONY : src/plugin.c.s

src/plugins/isometer.o: src/plugins/isometer.c.o

.PHONY : src/plugins/isometer.o

# target to build an object file
src/plugins/isometer.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/isometer.c.o
.PHONY : src/plugins/isometer.c.o

src/plugins/isometer.i: src/plugins/isometer.c.i

.PHONY : src/plugins/isometer.i

# target to preprocess a source file
src/plugins/isometer.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/isometer.c.i
.PHONY : src/plugins/isometer.c.i

src/plugins/isometer.s: src/plugins/isometer.c.s

.PHONY : src/plugins/isometer.s

# target to generate assembly for a file
src/plugins/isometer.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/isometer.c.s
.PHONY : src/plugins/isometer.c.s

src/plugins/pov.o: src/plugins/pov.c.o

.PHONY : src/plugins/pov.o

# target to build an object file
src/plugins/pov.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/pov.c.o
.PHONY : src/plugins/pov.c.o

src/plugins/pov.i: src/plugins/pov.c.i

.PHONY : src/plugins/pov.i

# target to preprocess a source file
src/plugins/pov.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/pov.c.i
.PHONY : src/plugins/pov.c.i

src/plugins/pov.s: src/plugins/pov.c.s

.PHONY : src/plugins/pov.s

# target to generate assembly for a file
src/plugins/pov.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/pov.c.s
.PHONY : src/plugins/pov.c.s

src/plugins/topdown.o: src/plugins/topdown.c.o

.PHONY : src/plugins/topdown.o

# target to build an object file
src/plugins/topdown.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/topdown.c.o
.PHONY : src/plugins/topdown.c.o

src/plugins/topdown.i: src/plugins/topdown.c.i

.PHONY : src/plugins/topdown.i

# target to preprocess a source file
src/plugins/topdown.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/topdown.c.i
.PHONY : src/plugins/topdown.c.i

src/plugins/topdown.s: src/plugins/topdown.c.s

.PHONY : src/plugins/topdown.s

# target to generate assembly for a file
src/plugins/topdown.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/plugins/topdown.c.s
.PHONY : src/plugins/topdown.c.s

src/proto/irc.o: src/proto/irc.c.o

.PHONY : src/proto/irc.o

# target to build an object file
src/proto/irc.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/proto/irc.c.o
.PHONY : src/proto/irc.c.o

src/proto/irc.i: src/proto/irc.c.i

.PHONY : src/proto/irc.i

# target to preprocess a source file
src/proto/irc.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/proto/irc.c.i
.PHONY : src/proto/irc.c.i

src/proto/irc.s: src/proto/irc.c.s

.PHONY : src/proto/irc.s

# target to generate assembly for a file
src/proto/irc.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/proto/irc.c.s
.PHONY : src/proto/irc.c.s

src/rng.o: src/rng.c.o

.PHONY : src/rng.o

# target to build an object file
src/rng.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/rng.c.o
.PHONY : src/rng.c.o

src/rng.i: src/rng.c.i

.PHONY : src/rng.i

# target to preprocess a source file
src/rng.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/rng.c.i
.PHONY : src/rng.c.i

src/rng.s: src/rng.c.s

.PHONY : src/rng.s

# target to generate assembly for a file
src/rng.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/rng.c.s
.PHONY : src/rng.c.s

src/savestat.o: src/savestat.c.o

.PHONY : src/savestat.o

# target to build an object file
src/savestat.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat.c.o
.PHONY : src/savestat.c.o

src/savestat.i: src/savestat.c.i

.PHONY : src/savestat.i

# target to preprocess a source file
src/savestat.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat.c.i
.PHONY : src/savestat.c.i

src/savestat.s: src/savestat.c.s

.PHONY : src/savestat.s

# target to generate assembly for a file
src/savestat.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat.c.s
.PHONY : src/savestat.c.s

src/savestat/s_bindmp.o: src/savestat/s_bindmp.c.o

.PHONY : src/savestat/s_bindmp.o

# target to build an object file
src/savestat/s_bindmp.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_bindmp.c.o
.PHONY : src/savestat/s_bindmp.c.o

src/savestat/s_bindmp.i: src/savestat/s_bindmp.c.i

.PHONY : src/savestat/s_bindmp.i

# target to preprocess a source file
src/savestat/s_bindmp.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_bindmp.c.i
.PHONY : src/savestat/s_bindmp.c.i

src/savestat/s_bindmp.s: src/savestat/s_bindmp.c.s

.PHONY : src/savestat/s_bindmp.s

# target to generate assembly for a file
src/savestat/s_bindmp.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_bindmp.c.s
.PHONY : src/savestat/s_bindmp.c.s

src/savestat/s_sqlite.o: src/savestat/s_sqlite.c.o

.PHONY : src/savestat/s_sqlite.o

# target to build an object file
src/savestat/s_sqlite.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_sqlite.c.o
.PHONY : src/savestat/s_sqlite.c.o

src/savestat/s_sqlite.i: src/savestat/s_sqlite.c.i

.PHONY : src/savestat/s_sqlite.i

# target to preprocess a source file
src/savestat/s_sqlite.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_sqlite.c.i
.PHONY : src/savestat/s_sqlite.c.i

src/savestat/s_sqlite.s: src/savestat/s_sqlite.c.s

.PHONY : src/savestat/s_sqlite.s

# target to generate assembly for a file
src/savestat/s_sqlite.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/savestat/s_sqlite.c.s
.PHONY : src/savestat/s_sqlite.c.s

src/scaffold.o: src/scaffold.c.o

.PHONY : src/scaffold.o

# target to build an object file
src/scaffold.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/scaffold.c.o
.PHONY : src/scaffold.c.o

src/scaffold.i: src/scaffold.c.i

.PHONY : src/scaffold.i

# target to preprocess a source file
src/scaffold.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/scaffold.c.i
.PHONY : src/scaffold.c.i

src/scaffold.s: src/scaffold.c.s

.PHONY : src/scaffold.s

# target to generate assembly for a file
src/scaffold.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/scaffold.c.s
.PHONY : src/scaffold.c.s

src/server.o: src/server.c.o

.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/server.c.s
.PHONY : src/server.c.s

src/storage/sqlite.o: src/storage/sqlite.c.o

.PHONY : src/storage/sqlite.o

# target to build an object file
src/storage/sqlite.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/storage/sqlite.c.o
.PHONY : src/storage/sqlite.c.o

src/storage/sqlite.i: src/storage/sqlite.c.i

.PHONY : src/storage/sqlite.i

# target to preprocess a source file
src/storage/sqlite.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/storage/sqlite.c.i
.PHONY : src/storage/sqlite.c.i

src/storage/sqlite.s: src/storage/sqlite.c.s

.PHONY : src/storage/sqlite.s

# target to generate assembly for a file
src/storage/sqlite.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/storage/sqlite.c.s
.PHONY : src/storage/sqlite.c.s

src/tilemap.o: src/tilemap.c.o

.PHONY : src/tilemap.o

# target to build an object file
src/tilemap.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tilemap.c.o
.PHONY : src/tilemap.c.o

src/tilemap.i: src/tilemap.c.i

.PHONY : src/tilemap.i

# target to preprocess a source file
src/tilemap.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tilemap.c.i
.PHONY : src/tilemap.c.i

src/tilemap.s: src/tilemap.c.s

.PHONY : src/tilemap.s

# target to generate assembly for a file
src/tilemap.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tilemap.c.s
.PHONY : src/tilemap.c.s

src/tnacl.o: src/tnacl.c.o

.PHONY : src/tnacl.o

# target to build an object file
src/tnacl.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tnacl.c.o
.PHONY : src/tnacl.c.o

src/tnacl.i: src/tnacl.c.i

.PHONY : src/tnacl.i

# target to preprocess a source file
src/tnacl.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tnacl.c.i
.PHONY : src/tnacl.c.i

src/tnacl.s: src/tnacl.c.s

.PHONY : src/tnacl.s

# target to generate assembly for a file
src/tnacl.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/tnacl.c.s
.PHONY : src/tnacl.c.s

src/twindow.o: src/twindow.c.o

.PHONY : src/twindow.o

# target to build an object file
src/twindow.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/twindow.c.o
.PHONY : src/twindow.c.o

src/twindow.i: src/twindow.c.i

.PHONY : src/twindow.i

# target to preprocess a source file
src/twindow.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/twindow.c.i
.PHONY : src/twindow.c.i

src/twindow.s: src/twindow.c.s

.PHONY : src/twindow.s

# target to generate assembly for a file
src/twindow.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/twindow.c.s
.PHONY : src/twindow.c.s

src/vm.o: src/vm.c.o

.PHONY : src/vm.o

# target to build an object file
src/vm.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm.c.o
.PHONY : src/vm.c.o

src/vm.i: src/vm.c.i

.PHONY : src/vm.i

# target to preprocess a source file
src/vm.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm.c.i
.PHONY : src/vm.c.i

src/vm.s: src/vm.c.s

.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm.c.s
.PHONY : src/vm.c.s

src/vm/duktapev.o: src/vm/duktapev.c.o

.PHONY : src/vm/duktapev.o

# target to build an object file
src/vm/duktapev.c.o:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm/duktapev.c.o
.PHONY : src/vm/duktapev.c.o

src/vm/duktapev.i: src/vm/duktapev.c.i

.PHONY : src/vm/duktapev.i

# target to preprocess a source file
src/vm/duktapev.c.i:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm/duktapev.c.i
.PHONY : src/vm/duktapev.c.i

src/vm/duktapev.s: src/vm/duktapev.c.s

.PHONY : src/vm/duktapev.s

# target to generate assembly for a file
src/vm/duktapev.c.s:
	$(MAKE) -f CMakeFiles/isekai.dir/build.make CMakeFiles/isekai.dir/src/vm/duktapev.c.s
.PHONY : src/vm/duktapev.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... isekai"
	@echo "... edit_cache"
	@echo "... libvcol"
	@echo "... camgraph"
	@echo "... libtwin"
	@echo "... camin"
	@echo "... libgoki"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/animate.o"
	@echo "... src/animate.i"
	@echo "... src/animate.s"
	@echo "... src/audition.o"
	@echo "... src/audition.i"
	@echo "... src/audition.s"
	@echo "... src/b64.o"
	@echo "... src/b64.i"
	@echo "... src/b64.s"
	@echo "... src/backlog.o"
	@echo "... src/backlog.i"
	@echo "... src/backlog.s"
	@echo "... src/callback.o"
	@echo "... src/callback.i"
	@echo "... src/callback.s"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/chunker.o"
	@echo "... src/chunker.i"
	@echo "... src/chunker.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/datafile.o"
	@echo "... src/datafile.i"
	@echo "... src/datafile.s"
	@echo "... src/datafile/xml.o"
	@echo "... src/datafile/xml.i"
	@echo "... src/datafile/xml.s"
	@echo "... src/ezxml.o"
	@echo "... src/ezxml.i"
	@echo "... src/ezxml.s"
	@echo "... src/files.o"
	@echo "... src/files.i"
	@echo "... src/files.s"
	@echo "... src/hs/hsdecode.o"
	@echo "... src/hs/hsdecode.i"
	@echo "... src/hs/hsdecode.s"
	@echo "... src/hs/hsencode.o"
	@echo "... src/hs/hsencode.i"
	@echo "... src/hs/hsencode.s"
	@echo "... src/ipc/netipc.o"
	@echo "... src/ipc/netipc.i"
	@echo "... src/ipc/netipc.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mobile.o"
	@echo "... src/mobile.i"
	@echo "... src/mobile.s"
	@echo "... src/plugin.o"
	@echo "... src/plugin.i"
	@echo "... src/plugin.s"
	@echo "... src/plugins/isometer.o"
	@echo "... src/plugins/isometer.i"
	@echo "... src/plugins/isometer.s"
	@echo "... src/plugins/pov.o"
	@echo "... src/plugins/pov.i"
	@echo "... src/plugins/pov.s"
	@echo "... src/plugins/topdown.o"
	@echo "... src/plugins/topdown.i"
	@echo "... src/plugins/topdown.s"
	@echo "... src/proto/irc.o"
	@echo "... src/proto/irc.i"
	@echo "... src/proto/irc.s"
	@echo "... src/rng.o"
	@echo "... src/rng.i"
	@echo "... src/rng.s"
	@echo "... src/savestat.o"
	@echo "... src/savestat.i"
	@echo "... src/savestat.s"
	@echo "... src/savestat/s_bindmp.o"
	@echo "... src/savestat/s_bindmp.i"
	@echo "... src/savestat/s_bindmp.s"
	@echo "... src/savestat/s_sqlite.o"
	@echo "... src/savestat/s_sqlite.i"
	@echo "... src/savestat/s_sqlite.s"
	@echo "... src/scaffold.o"
	@echo "... src/scaffold.i"
	@echo "... src/scaffold.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/storage/sqlite.o"
	@echo "... src/storage/sqlite.i"
	@echo "... src/storage/sqlite.s"
	@echo "... src/tilemap.o"
	@echo "... src/tilemap.i"
	@echo "... src/tilemap.s"
	@echo "... src/tnacl.o"
	@echo "... src/tnacl.i"
	@echo "... src/tnacl.s"
	@echo "... src/twindow.o"
	@echo "... src/twindow.i"
	@echo "... src/twindow.s"
	@echo "... src/vm.o"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
	@echo "... src/vm/duktapev.o"
	@echo "... src/vm/duktapev.i"
	@echo "... src/vm/duktapev.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

